"""add uq constract for fields app_type cluster_id and client_id

Revision ID: 0f5f712579f1
Revises: d24eb1329d9f
Create Date: 2026-02-18 15:17:19.305707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5f712579f1'
down_revision: Union[str, Sequence[str], None] = 'd24eb1329d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_peer_client_cluster_apptype', 'peers', ['client_id', 'cluster_id', 'app_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_peer_client_cluster_apptype', 'peers', type_='unique')
    # ### end Alembic commands ###
