"""add is admin field in clients model

Revision ID: 5f2be39f5bc0
Revises: 0f5f712579f1
Create Date: 2026-02-21 11:43:55.957960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2be39f5bc0'
down_revision: Union[str, Sequence[str], None] = '0f5f712579f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_admin')
    # ### end Alembic commands ###
