"""added new model tariff

Revision ID: a64f9d224f71
Revises: e040cd9ba6ca
Create Date: 2026-02-17 23:40:03.215844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64f9d224f71'
down_revision: Union[str, Sequence[str], None] = 'e040cd9ba6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price_rub', sa.Integer(), nullable=False),
    sa.Column('price_stars', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariffs_code'), 'tariffs', ['code'], unique=True)
    op.create_index(op.f('ix_tariffs_sort_order'), 'tariffs', ['sort_order'], unique=False)
    op.add_column('clients', sa.Column('subscription_status', sa.String(length=50), nullable=False))
    op.add_column('clients', sa.Column('trial_used', sa.Boolean(), nullable=False))
    op.add_column('clients', sa.Column('last_subscription_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'last_subscription_at')
    op.drop_column('clients', 'trial_used')
    op.drop_column('clients', 'subscription_status')
    op.drop_index(op.f('ix_tariffs_sort_order'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_code'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
