"""edit cluster and peer models fields

Revision ID: dca912ffabca
Revises: e5001e68dc64
Create Date: 2026-02-11 14:43:49.562919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca912ffabca'
down_revision: Union[str, Sequence[str], None] = 'e5001e68dc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peers', sa.Column('cluster_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_peers_cluster_id'), 'peers', ['cluster_id'], unique=False)
    op.create_foreign_key(None, 'peers', 'clusters', ['cluster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'peers', type_='foreignkey')
    op.drop_index(op.f('ix_peers_cluster_id'), table_name='peers')
    op.drop_column('peers', 'cluster_id')
    # ### end Alembic commands ###
