"""added state fields into ClusterModel

Revision ID: e040cd9ba6ca
Revises: dca912ffabca
Create Date: 2026-02-12 18:25:06.211338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e040cd9ba6ca'
down_revision: Union[str, Sequence[str], None] = 'dca912ffabca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('container_status', sa.String(length=50), nullable=True))
    op.add_column('clusters', sa.Column('container_name', sa.String(length=255), nullable=True))
    op.add_column('clusters', sa.Column('protocol', sa.String(length=50), nullable=True))
    op.add_column('clusters', sa.Column('peers_count', sa.Integer(), nullable=False))
    op.add_column('clusters', sa.Column('online_peers_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clusters', 'online_peers_count')
    op.drop_column('clusters', 'peers_count')
    op.drop_column('clusters', 'protocol')
    op.drop_column('clusters', 'container_name')
    op.drop_column('clusters', 'container_status')
    # ### end Alembic commands ###
