"""edit host and port fielt in cluster model to endpoint field

Revision ID: e5001e68dc64
Revises: 9ab7c0c9b3be
Create Date: 2026-02-11 12:45:36.737920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5001e68dc64'
down_revision: Union[str, Sequence[str], None] = '9ab7c0c9b3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('endpoint', sa.String(length=255), nullable=False))
    op.add_column('clusters', sa.Column('api_key', sa.String(length=255), nullable=False))
    op.drop_column('clusters', 'host')
    op.drop_column('clusters', 'api_key_hash')
    op.drop_column('clusters', 'port')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clusters', sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('api_key_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('clusters', 'api_key')
    op.drop_column('clusters', 'endpoint')
    # ### end Alembic commands ###
